name: Optimize icons
on:
  pull_request:
    paths:
      - 'icons/**/*.svg'
      - '.github/scripts/svgo.config.js'
      - '.github/workflows/optimize-icons.yml'
    types: [opened, synchronize, edited ]

jobs:
  optimize:
    runs-on: ubuntu-latest
    name: Optimize icons with SVGO
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: ericcornelissen/svgo-action@v3
        id: svgo
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          svgo-config: ./.github/scripts/svgo.config.js
          svgo-version: 3

      - name: suggester / svgo
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: svgo
          token: ${{ secrets.GITHUB_TOKEN }}
